# Generated by Django 4.1.3 on 2022-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body_quession', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['publish'],
            },
        ),
    ]
