# Generated by Django 4.1.3 on 2022-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quession',
            name='body_answer',
            field=models.TextField(default=''),
        ),
    ]
