# Generated by Django 4.1.3 on 2022-11-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_quession_body_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quession',
            old_name='body_quession',
            new_name='quession',
        ),
    ]
